### ISSUE TITLE
Unknown language in Cody Archive

### ISSUE THREAD

**Issue by lweakly** [CDRH/cocoon_cody#7]
I have new foreign language materials coming and will need the site to reflect these languages. Right now, I think only the German materials display properly. I have added two files in French (this is one: http://codyarchive.org/memorabilia/wfc.mem00020.html) and will have one in Italian coming soon. 

I am using ISO 639-1 Code (http://www.loc.gov/standards/iso639-2/php/code_list.php)

In addition to German, the languages that are coming right away are French (fr) and Italian (it). Coming later will be Spanish (es) and (el) and possibly others.

<img width="355" alt="screen shot 2018-06-01 at 2 23 08 pm" src="https://user-images.githubusercontent.com/6775622/40859435-719ec600-65a7-11e8-8b45-25dcc780bdd2.png">

**Comment by karindalziel** [comment]
I think this is fixed!

https://cdrhdev1.unl.edu/cocoon/codyarchive.org/texts/wfc.mem00020.html

Test it out and I'll pull changes to live site

**Comment by karindalziel** [comment]
Pulled onto live site, closing issue
